"""add catogeries m2m

Revision ID: ef35761ad3b0
Revises: 86e805aecaff
Create Date: 2023-11-12 22:15:50.466808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef35761ad3b0'
down_revision: Union[str, None] = '86e805aecaff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avert_to_categ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_advert', sa.Integer(), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_advert'], ['advertisement.id'], ),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avert_to_categ')
    op.drop_table('categories')
    # ### end Alembic commands ###
